import { Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import {Toaster} from '@/components/ui/sonner'
import DarkNavbar  from '@/components/page/Navbar'

import { NavProvider } from "@/components/contexts/NavigationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"], 
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-lora",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} antialiased bg-black`}
      >
        <NavProvider>
          <DarkNavbar 
            desktopClassName="custom-desktop-styles"
            mobileClassName="custom-mobile-styles" 
          />
          {children}
          <Toaster />
        </NavProvider>
      </body>
    </html>
  );
}
